export const cardList = [
  {
    id: 1,
    topic: "Web Design",
    title: "Сделать дизайн главной страницы",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    title: "Проанализировать конкурентов",
    date: "29.10.23",
    status: "Нужно сделать",
  },
  {
    id: 3,
    topic: "Copywriting",
    title: "Написать тексты для сайта",
    date: "28.10.23",
    status: "В работе",
  },
  {
    id: 4,
    topic: "Research",
    title: "Провести интервью с пользователями",
    date: "27.10.23",
    status: "Тестирование",
  },
  {
    id: 5,
    topic: "Web Design",
    title: "Создать макет мобильной версии",
    date: "26.10.23",
    status: "Готово",
  },
  {
    id: 6,
    topic: "Research",
    title: "Собрать обратную связь",
    date: "25.10.23",
    status: "Без статуса",
  },
  {
    id: 7,
    topic: "Copywriting",
    title: "Отредактировать контент",
    date: "24.10.23",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Web Design",
    title: "Доработать дизайн формы",
    date: "23.10.23",
    status: "В работе",
  },
  {
    id: 9,
    topic: "Research",
    title: "Изучить аналитику",
    date: "22.10.23",
    status: "Нужно сделать",
  },
];
